### ISSUE TITLE
Snowflake streaming ingest : Uncommitted rows due to server side errors

### ISSUE THREAD

**Issue by vamsikt** [snowflakedb/snowflake-ingest-java#351]
Hi,

We are testing out the the snowflake streaming ingest api using the example https://github.com/snowflakedb/snowflake-ingest-java/blob/master/src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java

and seeing the following error

One or more channels [Channel name] might contain uncommitted rows due to server side errors,
please consider reopening the channels to replay the data loading by using the latest persistent offset token..

but the getLatestCommittedOffsetToken will always returning null...
- how can we suppress this error and replay messages?
- Is there any way to see the server side error using snowsight/query?

**Comment by sfc-gh-japatel** [comment]
Few questions:
1. Which version of SDK?
2. Have you reopened the channel?
3. Were you successful in ingesting data ever before? 
4. You can run `show channels in table <table_name>`

**Comment by vamsikt** [comment]
@sfc-gh-japatel 
1. Which version of SDK?
     - 1.1.0
2. Have you reopened the channel?
     - Re running same channel also giving same error
3. Were you successful in ingesting data ever before?
    - No, I was not able to ingest any data
4. You can run show channels in table <table_name>
    - I see the offset_token value as as null for the channel I created.

**Comment by sfc-gh-japatel** [comment]
Try reopening the channel using openChannel API. Can you share more logs? There should be error code somewhere

**Comment by vamsikt** [comment]
Exception in thread "main" java.util.concurrent.ExecutionException: net.snowflake.ingest.utils.SFException: One or more channels [XXXXXX] might contain uncommitted rows due to server side errors, please consider reopening the channels to replay the data loading by using the latest persistent offset token.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
at SnowflakeStreamingIngestExample.java:96
Caused by: net.snowflake.ingest.utils.SFException: One or more channels [XXXXXX] might contain uncommitted rows due to server side errors, please consider reopening the channels to replay the data loading by using the latest persistent offset token.
at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.lambda$close$0(SnowflakeStreamingIngestChannelInternal.java:299)
at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
at java.util.concurrent.CompletableFuture$UniRun.tryFire$$$capture(CompletableFuture.java:687)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java)
at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157

**Comment by vamsikt** [comment]
I am using the example for streaming ingest the https://github.com/snowflakedb/snowflake-ingest-java/blob/master/src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java

**Comment by vamsikt** [comment]
@sfc-gh-japatel also re-opened the channel and re ran the inserts but still getting same error.

**Comment by sfc-gh-japatel** [comment]
> Author

Are you ensuring that you use your own profile.json?

**Comment by vamsikt** [comment]
@sfc-gh-japatel yes I am using my own profile.json..
I was able to list the channels I created in snowsight and all of them has null as `offset_token`

**Comment by sfc-gh-japatel** [comment]
Thanks @vamsikt for all information. This still wont help us identify root cause. 

Couple of things to try:
1. Create or replace the table. 
2. Enable debug logging for your run and send logs which has more info around the error. 
Thanks

**Comment by sfc-gh-japatel** [comment]
Also send us account name, db, sc, table name. I will debug on server side about error.

**Comment by vamsikt** [comment]
@sfc-gh-japatel can you share the contact info as I can not share those details here or we can open a support ticket with the  snowflake team.

**Comment by vamsikt** [comment]
> Thanks @vamsikt for all information. This still wont help us identify root cause.
> 
> Couple of things to try:
> 
> 1. Create or replace the table.
> 2. Enable debug logging for your run and send logs which has more info around the error.
>    Thanks

I will try this.

**Comment by sfc-gh-rsharma** [comment]
@sfc-gh-japatel Kindly note that the issue is resolved now under case 00497292. The issue was related to the JDK version not supporting unlimited cryptography strength.

**Comment by sfc-gh-japatel** [comment]
Sounds good! Please update this issue as well so that other users can see the fix. 
CC: @sfc-gh-rsharma @vamsikt 
Thank you

**Comment by sfc-gh-xhuang** [comment]
Snowpipe Streaming only supports 256-bit keys for encryption of data.

The Snowpipe Streaming SDK supports Java version 8 (or higher) and requires Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files. Some installations of Java 8 may not have included Unlimited Strength Jurisdiction Policy Files to support using 256-bit encryption. 

We will amend our documentation to call this out and also surface the exception regarding unsupported 128 bit keys earlier
