### ISSUE TITLE
[possible bug] not a valid hex string

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-ingest-java#587]
Hi, we're seeing the following exception for one of our Snowflake Kafka Connectors. Currently we're on Snowflake Kafka Connector v2.0.0. The topics it is consuming from are created and populated by a Debezium MySQL Connector v2.3.1.Final with mostly default settings.

```
[destination_65019e4b368473fede109f76|task-0] Error encountered in task destination_65019e4b368473fede109f76-0. Executing stage 'TASK_PUT' with class 'org.apache.kafka.connect.sink.SinkTask'. (org.apache.kafka.connect.runtime.errors.LogReporter)
net.snowflake.ingest.utils.SFException: The given row cannot be converted to the internal format due to invalid value: Value cannot be ingested into Snowflake column SUITE_ORDER_UUID of type BINARY, Row Index: 0, reason: Not a valid hex string
	at net.snowflake.ingest.streaming.internal.DataValidationUtil.valueFormatNotAllowedException(DataValidationUtil.java:884)
	at net.snowflake.ingest.streaming.internal.DataValidationUtil.validateAndParseBinary(DataValidationUtil.java:626)
	at net.snowflake.ingest.streaming.internal.ParquetValueParser.getBinaryValueForLogicalBinary(ParquetValueParser.java:420)
	at net.snowflake.ingest.streaming.internal.ParquetValueParser.parseColumnValueToParquet(ParquetValueParser.java:147)
	at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.addRow(ParquetRowBuffer.java:203)
	at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.addRow(ParquetRowBuffer.java:148)
	at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:306)
	at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.insertRows(ParquetRowBuffer.java:35)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:362)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRow(SnowflakeStreamingIngestChannelInternal.java:328)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:632)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:584)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:182)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:438)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertRowsWithFallback(TopicPartitionChannel.java:578)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:504)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecordsIfFlushTimeThresholdReached(TopicPartitionChannel.java:485)
	at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.insert(SnowflakeSinkServiceV2.java:238)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:584)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run
```

The topic and field's schema definition (we're using the Confluent Schema Registry) is as follows:
```
{
   "string":"source_6500a3e37ebfaf528f7ce3d6.orders_xref-value",
   "schemaId":7870,
   "version":1,
   "compatibility":"NONE",
   "schema":{
      "type":"record",
      "name":"Value",
      "namespace":"source_6500a3e37ebfaf528f7ce3d6.orders_xref",
      "fields": [
         {
            "name":"order_id",
            "type":"int"
         },
         {
            "name":"device_order_uuid",
            "type":["null","bytes"],
            "default":NULL
         },
         {
            "name":"tipStatus",
            "type":["null",
               {
                  "type":"int",
                  "connect.type":"int16"
               }
            ],
            "default":NULL
         },
         {
            "name":"guestCount",
            "type":["null","int"],
            "default":NULL
         },
         {
            "name":"date_modified",
            "type":{
               "type":"string",
               "connect.version":1,
               "connect.default":"1970-01-01T00:00:00Z",
               "connect.name":"io.debezium.time.ZonedTimestamp"
            },
            "default":"1970-01-01T00:00:00Z"
         },
         {
            "name":"visitor_id",
            "type":["null","string"],
            "default":NULL
         },
         {
            "name":"_streamkap_source_ts_ms",
            "type":["null","long"],
            "default":NULL
         },
         {
            "name":"_streamkap_ts_ms",
            "type":["null","long"],
            "default":NULL
         },
         {
            "name":"__deleted",
            "type":[""null","string"],
            "default":NULL
         }
      ],
      "connect.name":"source_6500a3e37ebfaf528f7ce3d6.orders_xref.Value"
   },
   "registeredVersions":[1],
   "type":"AVRO"
}
```

The reason we _think_ this may be a bug is, the Snowflake Kafka Connector seems to [accept and handle Connect Record fields of `BYTES` type](https://github.com/snowflakedb/snowflake-kafka-connector/blob/c7c440b78dcefc76991fde5789991a3e45c95bf4/src/main/java/com/snowflake/kafka/connector/records/RecordService.java#L411), but goes on to throw an exception in the Ingest SDK [here](https://github.com/snowflakedb/snowflake-ingest-java/blob/605f32829244f720c2a1118538fff00e37738a88/src/main/java/net/snowflake/ingest/streaming/internal/DataValidationUtil.java#L597) where it's treating it as a `String` type?

A workaround - at least for Debezium Connectors - is to change their [binary.handling.mode](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-property-binary-handling-mode).

**Comment by JonathonO** [comment]
Hi @sfc-gh-xhuang any ideas about the above? Appreciate I only raised it at the end of last week though so there's not been much time. I also realised the first link (Snowflake Connector `RecordService` link) was wrong, sorry. I've now corrected that.

**Comment by JonathonO** [comment]
> @JonathonO Let us triage this this week.

Thank you, much appreciated as always 🙇‍♂️

**Comment by JonathonO** [comment]
This issue may actually be in Snowflake Kafka Connector. My colleague's raised a separate issue ticket here: https://github.com/snowflakedb/snowflake-kafka-connector/issues/704

**Comment by sfc-gh-rcheng** [comment]
@JonathonO are you able to repro and share your KC logs for this issue? I've tried numerous different inputs, but I've only been able to error out in Kafka Connector, not in the ingestSDK

**Comment by JonathonO** [comment]
> @JonathonO are you able to repro and share your KC logs for this issue? I've tried numerous different inputs, but I've only been able to error out in Kafka Connector, not in the ingestSDK

@sfc-gh-rcheng we'll repro and share logs as soon we can but it's likely to be some days yet, sorry.
