### ISSUE TITLE
Client configure request failed

### ISSUE THREAD

**Issue by szkoludasebastian** [snowflakedb/snowflake-ingest-java#820]
During ingesting data we noticed this kind of error:

`net.snowflake.ingest.utils.SFException: Client configure request failed: Timeout waiting for connection from pool. at net.snowflake.ingest.streaming.internal.InternalStageManager.<init>(InternalStageManager.java:95) at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.<init>(SnowflakeStreamingIngestClientInternal.java:226) at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.<init>(SnowflakeStreamingIngestClientInternal.java:261) at net.snowflake.ingest.streaming.SnowflakeStreamingIngestClientFactory$Builder.build(SnowflakeStreamingIngestClientFactory.java:60) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeClientFactory.createClient(SnowflakeClientFactory.java:22) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeConnectionPool.initializeSnowflakeClient(SnowflakeConnectionPool.java:127) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeConnectionPool.createSnowflakeChannel(SnowflakeConnectionPool.java:117) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeConnectionPool.lambda$getConnection$0(SnowflakeConnectionPool.java:80) at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeConnectionPool.getConnection(SnowflakeConnectionPool.java:78) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeConnectionPool.getConnection(SnowflakeConnectionPool.java:56) at com.infor.datalake.ingestion.streaming.offloader.pipeline.adapter.outbound.db.api.snowflake.service.SnowflakeApiConnectionService.createOrGetConnection(SnowflakeApiConnectionService.java:30) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64) ... 25 common frames omitted Caused by: net.snowflake.client.jdbc.internal.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool at net.snowflake.client.jdbc.internal.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316) at net.snowflake.client.jdbc.internal.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282) at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85) at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) at net.snowflake.client.jdbc.internal.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) at net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) at net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) at net.snowflake.ingest.streaming.internal.StreamingIngestUtils.executeWithRetries(StreamingIngestUtils.java:135) at net.snowflake.ingest.streaming.internal.StreamingIngestUtils.executeWithRetries(StreamingIngestUtils.java:109) at net.snowflake.ingest.streaming.internal.StreamingIngestUtils.executeWithRetries(StreamingIngestUtils.java:95) at net.snowflake.ingest.streaming.internal.SnowflakeServiceClient.executeApiRequestWithRetries(SnowflakeServiceClient.java:190) at net.snowflake.ingest.streaming.internal.SnowflakeServiceClient.clientConfigure(SnowflakeServiceClient.java:61) at net.snowflake.ingest.streaming.internal.InternalStageManager.<init>(InternalStageManager.java:73) ... 43 common frames omitted`

Do you know maybe what could be the reason of this error?

**Comment by sfc-gh-xhuang** [comment]
@szkoludasebastian Which sdk version are you using that hits this? 
how often does this occur and when? Is it during the open channels request? 

Please open a support case with some logs as that will help us debug further with you
